local ADDON_NAME, DL = ...

DL.Locale = {
  EN = {
    ADDON_NAME = "Duolingwow",
    OPTIONS_TITLE = "Duolingwow Options",
    OPTIONS_DESC = "Select languages to show in abbreviation tooltips.",
    OPTIONS_LANG_HEADER = "Languages",
    OPTIONS_EXTENSION_HEADER = "Extensions",
    OPTIONS_TYPE_HEADER = "Zone types",
    OPTIONS_CREDITS_HEADER = "Credits",
    OPTIONS_CREDITS = "Author: Poro",
    OPTIONS_GITHUB = "GitHub: https://github.com/poro/duolingwow",
    OPTIONS_COLOR_HEADER = "Chat Link Color",
    OPTIONS_COLOR_PICKER = "Choose link color",
    OPTIONS_BLOCKLIST_HEADER = "Tooltip blocklist",
    OPTIONS_BLOCKLIST_DESC = "Disable tooltips for specific abbreviation keys.",
    OPTIONS_BLOCKLIST_PLACEHOLDER = "Example: LFG",
    OPTIONS_BLOCKLIST_ADD = "Add",
    OPTIONS_BLOCKLIST_REMOVE = "Remove",
    OPTIONS_BLOCKLIST_CLEAR = "Clear",
    OPTIONS_BLOCKLIST_EMPTY = "No blocked keys.",
    OPTIONS_BLOCKLIST_LIST = "Blocked keys: %s",
    TOOLTIP_TITLE = "Duolingwow",
    TOOLTIP_EMPTY = "No entry for enabled languages.",
    TOOLTIP_EXTENSION = "Extension:",
    TOOLTIP_TYPE = "Type:",
    EXTENSION_VANILLA = "Vanilla",
    EXTENSION_TBC = "The Burning Crusade",
    ZONE_TYPE_RAID = "Raid",
    ZONE_TYPE_DUNGEON = "Dungeon",
    ZONE_TYPE_ZONE = "Zone",
    ZONE_TYPE_BATTLEGROUND = "Battleground",
    ZONE_TYPE_CITY = "City",
    ZONE_TYPE_ARENA = "Arena",
    COMMAND_PREFIX = "Duolingwow commands:",
    COMMAND_HELP = "/dl help - show this help",
    COMMAND_ENABLE = "/dl lang enable <lang> - enable a language (EN/FR/DE)",
    COMMAND_DISABLE = "/dl lang disable <lang> - disable a language (EN/FR/DE)",
    COMMAND_EXTENSION_ENABLE = "/dl extension enable <extension> - enable an extension (Vanilla/TBC)",
    COMMAND_EXTENSION_DISABLE = "/dl extension disable <extension> - disable an extension (Vanilla/TBC)",
    COMMAND_TYPE_ENABLE = "/dl type enable <type> - enable a zone type (Raid/Dungeon/Zone/Battleground/City/Arena)",
    COMMAND_TYPE_DISABLE = "/dl type disable <type> - disable a zone type (Raid/Dungeon/Zone/Battleground/City/Arena)",
    COMMAND_BLOCKLIST_HELP = "/dl blocklist <add/remove/list/clear> <key> - manage tooltip blocklist",
    COMMAND_STATUS = "/dl status - show enabled filters",
    COMMAND_UNKNOWN = "Unknown command. Use /dl help.",
    COMMAND_LANG_UNKNOWN = "Unknown language: %s",
    COMMAND_LANG_UPDATED = "%s language is now %s.",
    COMMAND_EXTENSION_UNKNOWN = "Unknown extension: %s",
    COMMAND_EXTENSION_UPDATED = "%s extension is now %s.",
    COMMAND_TYPE_UNKNOWN = "Unknown zone type: %s",
    COMMAND_TYPE_UPDATED = "%s zone type is now %s.",
    COMMAND_STATUS_LINE = "Enabled languages: %s.",
    COMMAND_STATUS_EXTENSIONS_LINE = "Enabled extensions: %s.",
    COMMAND_STATUS_TYPES_LINE = "Enabled zone types: %s.",
    COMMAND_STATUS_BLOCKLIST_LINE = "Blocked tooltip keys: %s.",
    COMMAND_BLOCKLIST_MISSING = "Please provide a key to block or unblock.",
    COMMAND_BLOCKLIST_ADDED = "Blocked tooltip key: %s.",
    COMMAND_BLOCKLIST_REMOVED = "Unblocked tooltip key: %s.",
    COMMAND_BLOCKLIST_CLEARED = "Cleared tooltip blocklist.",
    COMMAND_BLOCKLIST_LIST = "Blocked tooltip keys: %s.",
  },
  FR = {
    ADDON_NAME = "Duolingwow",
    OPTIONS_TITLE = "Options Duolingwow",
    OPTIONS_DESC = "Sélectionnez les langues à afficher dans les tooltips.",
    OPTIONS_LANG_HEADER = "Langues",
    OPTIONS_EXTENSION_HEADER = "Extensions",
    OPTIONS_TYPE_HEADER = "Types de zone",
    OPTIONS_CREDITS_HEADER = "Crédits",
    OPTIONS_CREDITS = "Auteur : Poro",
    OPTIONS_GITHUB = "GitHub : https://github.com/poro/duolingwow",
    OPTIONS_COLOR_HEADER = "Couleur du lien de chat",
    OPTIONS_COLOR_PICKER = "Choisir la couleur",
    OPTIONS_BLOCKLIST_HEADER = "Blocklist des tooltips",
    OPTIONS_BLOCKLIST_DESC = "Désactive les tooltips pour certaines clés d'abréviation.",
    OPTIONS_BLOCKLIST_PLACEHOLDER = "Exemple : LFG",
    OPTIONS_BLOCKLIST_ADD = "Ajouter",
    OPTIONS_BLOCKLIST_REMOVE = "Retirer",
    OPTIONS_BLOCKLIST_CLEAR = "Vider",
    OPTIONS_BLOCKLIST_EMPTY = "Aucune clé bloquée.",
    OPTIONS_BLOCKLIST_LIST = "Clés bloquées : %s",
    TOOLTIP_TITLE = "Duolingwow",
    TOOLTIP_EMPTY = "Aucune entrée pour les langues activées.",
    TOOLTIP_EXTENSION = "Extension :",
    TOOLTIP_TYPE = "Type :",
    EXTENSION_VANILLA = "Vanilla",
    EXTENSION_TBC = "The Burning Crusade",
    ZONE_TYPE_RAID = "Raid",
    ZONE_TYPE_DUNGEON = "Donjon",
    ZONE_TYPE_ZONE = "Zone",
    ZONE_TYPE_BATTLEGROUND = "Champ de bataille",
    ZONE_TYPE_CITY = "Ville",
    ZONE_TYPE_ARENA = "Arène",
    COMMAND_PREFIX = "Commandes Duolingwow :",
    COMMAND_HELP = "/dl help - afficher cette aide",
    COMMAND_ENABLE = "/dl lang enable <lang> - activer une langue (EN/FR/DE)",
    COMMAND_DISABLE = "/dl lang disable <lang> - désactiver une langue (EN/FR/DE)",
    COMMAND_EXTENSION_ENABLE = "/dl extension enable <extension> - activer une extension (Vanilla/TBC)",
    COMMAND_EXTENSION_DISABLE = "/dl extension disable <extension> - désactiver une extension (Vanilla/TBC)",
    COMMAND_TYPE_ENABLE = "/dl type enable <type> - activer un type de zone (Raid/Donjon/Zone/Champ de bataille/Ville/Arène)",
    COMMAND_TYPE_DISABLE = "/dl type disable <type> - désactiver un type de zone (Raid/Donjon/Zone/Champ de bataille/Ville/Arène)",
    COMMAND_BLOCKLIST_HELP = "/dl blocklist <add/remove/list/clear> <clé> - gérer la blocklist des tooltips",
    COMMAND_STATUS = "/dl status - afficher les filtres activés",
    COMMAND_UNKNOWN = "Commande inconnue. Utilisez /dl help.",
    COMMAND_LANG_UNKNOWN = "Langue inconnue : %s",
    COMMAND_LANG_UPDATED = "Langue %s %s.",
    COMMAND_EXTENSION_UNKNOWN = "Extension inconnue : %s",
    COMMAND_EXTENSION_UPDATED = "Extension %s %s.",
    COMMAND_TYPE_UNKNOWN = "Type de zone inconnu : %s",
    COMMAND_TYPE_UPDATED = "Type de zone %s %s.",
    COMMAND_STATUS_LINE = "Langues activées : %s.",
    COMMAND_STATUS_EXTENSIONS_LINE = "Extensions activées : %s.",
    COMMAND_STATUS_TYPES_LINE = "Types de zone activés : %s.",
    COMMAND_STATUS_BLOCKLIST_LINE = "Clés de tooltip bloquées : %s.",
    COMMAND_BLOCKLIST_MISSING = "Merci de fournir une clé à bloquer ou débloquer.",
    COMMAND_BLOCKLIST_ADDED = "Clé de tooltip bloquée : %s.",
    COMMAND_BLOCKLIST_REMOVED = "Clé de tooltip débloquée : %s.",
    COMMAND_BLOCKLIST_CLEARED = "Blocklist des tooltips vidée.",
    COMMAND_BLOCKLIST_LIST = "Clés de tooltip bloquées : %s.",
  },
  DE = {
    ADDON_NAME = "Duolingwow",
    OPTIONS_TITLE = "Duolingwow-Optionen",
    OPTIONS_DESC = "Wähle die Sprachen für die Abkürzungs-Tooltips.",
    OPTIONS_LANG_HEADER = "Sprachen",
    OPTIONS_EXTENSION_HEADER = "Erweiterungen",
    OPTIONS_TYPE_HEADER = "Zonentypen",
    OPTIONS_CREDITS_HEADER = "Credits",
    OPTIONS_CREDITS = "Autor: Poro",
    OPTIONS_GITHUB = "GitHub: https://github.com/poro/duolingwow",
    OPTIONS_COLOR_HEADER = "Chat-Link-Farbe",
    OPTIONS_COLOR_PICKER = "Linkfarbe wählen",
    OPTIONS_BLOCKLIST_HEADER = "Tooltip-Blockliste",
    OPTIONS_BLOCKLIST_DESC = "Deaktiviert Tooltips für bestimmte Abkürzungsschlüssel.",
    OPTIONS_BLOCKLIST_PLACEHOLDER = "Beispiel: LFG",
    OPTIONS_BLOCKLIST_ADD = "Hinzufügen",
    OPTIONS_BLOCKLIST_REMOVE = "Entfernen",
    OPTIONS_BLOCKLIST_CLEAR = "Leeren",
    OPTIONS_BLOCKLIST_EMPTY = "Keine blockierten Schlüssel.",
    OPTIONS_BLOCKLIST_LIST = "Blockierte Schlüssel: %s",
    TOOLTIP_TITLE = "Duolingwow",
    TOOLTIP_EMPTY = "Kein Eintrag für aktivierte Sprachen.",
    TOOLTIP_EXTENSION = "Erweiterung:",
    TOOLTIP_TYPE = "Typ:",
    EXTENSION_VANILLA = "Vanilla",
    EXTENSION_TBC = "The Burning Crusade",
    ZONE_TYPE_RAID = "Raid",
    ZONE_TYPE_DUNGEON = "Dungeon",
    ZONE_TYPE_ZONE = "Zone",
    ZONE_TYPE_BATTLEGROUND = "Schlachtfeld",
    ZONE_TYPE_CITY = "Stadt",
    ZONE_TYPE_ARENA = "Arena",
    COMMAND_PREFIX = "Duolingwow-Befehle:",
    COMMAND_HELP = "/dl help - diese Hilfe anzeigen",
    COMMAND_ENABLE = "/dl lang enable <lang> - Sprache aktivieren (EN/FR/DE)",
    COMMAND_DISABLE = "/dl lang disable <lang> - Sprache deaktivieren (EN/FR/DE)",
    COMMAND_EXTENSION_ENABLE = "/dl extension enable <extension> - Erweiterung aktivieren (Vanilla/TBC)",
    COMMAND_EXTENSION_DISABLE = "/dl extension disable <extension> - Erweiterung deaktivieren (Vanilla/TBC)",
    COMMAND_TYPE_ENABLE = "/dl type enable <type> - Zonentyp aktivieren (Raid/Dungeon/Zone/Schlachtfeld/Stadt/Arena)",
    COMMAND_TYPE_DISABLE = "/dl type disable <type> - Zonentyp deaktivieren (Raid/Dungeon/Zone/Schlachtfeld/Stadt/Arena)",
    COMMAND_BLOCKLIST_HELP = "/dl blocklist <add/remove/list/clear> <key> - Tooltip-Blockliste verwalten",
    COMMAND_STATUS = "/dl status - aktivierte Filter anzeigen",
    COMMAND_UNKNOWN = "Unbekannter Befehl. Nutze /dl help.",
    COMMAND_LANG_UNKNOWN = "Unbekannte Sprache: %s",
    COMMAND_LANG_UPDATED = "Sprache %s ist jetzt %s.",
    COMMAND_EXTENSION_UNKNOWN = "Unbekannte Erweiterung: %s",
    COMMAND_EXTENSION_UPDATED = "Erweiterung %s ist jetzt %s.",
    COMMAND_TYPE_UNKNOWN = "Unbekannter Zonentyp: %s",
    COMMAND_TYPE_UPDATED = "Zonentyp %s ist jetzt %s.",
    COMMAND_STATUS_LINE = "Aktivierte Sprachen: %s.",
    COMMAND_STATUS_EXTENSIONS_LINE = "Aktivierte Erweiterungen: %s.",
    COMMAND_STATUS_TYPES_LINE = "Aktivierte Zonentypen: %s.",
    COMMAND_STATUS_BLOCKLIST_LINE = "Blockierte Tooltip-Schlüssel: %s.",
    COMMAND_BLOCKLIST_MISSING = "Bitte gib einen Schlüssel an, der blockiert werden soll.",
    COMMAND_BLOCKLIST_ADDED = "Tooltip-Schlüssel blockiert: %s.",
    COMMAND_BLOCKLIST_REMOVED = "Tooltip-Schlüssel freigegeben: %s.",
    COMMAND_BLOCKLIST_CLEARED = "Tooltip-Blockliste geleert.",
    COMMAND_BLOCKLIST_LIST = "Blockierte Tooltip-Schlüssel: %s.",
  },
}

function DL:GetAvailableLanguages()
  return {
    { code = "EN", name = "English" },
    { code = "FR", name = "Français" },
    { code = "DE", name = "Deutsch" },
  }
end

function DL:GetStrings(locale)
  if locale == "EN" or locale == "FR" or locale == "DE" then
    return self.Locale[locale]
  end
  local gameLocale = GetLocale()
  if gameLocale == "frFR" then
    return self.Locale.FR
  end
  if gameLocale == "deDE" then
    return self.Locale.DE
  end
  return self.Locale.EN
end

function DL:GetAvailableExtensions(locale)
  local L = self:GetStrings(locale or nil)
  return {
    { code = "VANILLA", name = L.EXTENSION_VANILLA },
    { code = "TBC", name = L.EXTENSION_TBC },
  }
end

function DL:GetAvailableZoneTypes(locale)
  local L = self:GetStrings(locale or nil)
  return {
    { code = "RAID", name = L.ZONE_TYPE_RAID },
    { code = "DUNGEON", name = L.ZONE_TYPE_DUNGEON },
    { code = "ZONE", name = L.ZONE_TYPE_ZONE },
    { code = "BATTLEGROUND", name = L.ZONE_TYPE_BATTLEGROUND },
    { code = "CITY", name = L.ZONE_TYPE_CITY },
    { code = "ARENA", name = L.ZONE_TYPE_ARENA },
  }
end
